tulika-99/sorting-algorithms

- BubbleSortCSharp/BubbleSort.cs
- BubbleSortCSharp/Bubblesort.txt
> BubbleSortCSharp

- Insertion-sort-Java/algoritm.txt
- Insertion-sort-Java/insertion sort
insertion sort using  java with example and algorithm.
> insertions sort-java

- Insertion Sort/Insertion-sort-C++/Insertion Sort.cpp
- Insertion Sort/Insertion-sort-C++/algoritm.txt
This pull request is being made to add Insertion Sort algorithm implementation using C++. The algorithm.txt file remains same since only the language used to implement the Insertion Sort algorithm has changed.
Thank you!
> Added Insertion Sort Algorithm in C++ language

- Insertion Sort/Insertion-sort-Dart/algorithm.txt
- Insertion Sort/Insertion-sort-Dart/insertion_sort.dart
Added InsertionSort in Dart with algorithm.txt
> Added InsertionSort-Dart

- Insertion Sort/Insertion-sort-C/Insertion-Sort-C.c
Insertion Sort in C language has been implemented. 
Note :
By default, maximum size of the array is set to MAXSIZE which is 100.
If the maximum size of the array is to be changed, then kindly update the value of MAXSIZE to the necessary value.
> Insertion Sort in C has been implemented.

- CountingSort.py
> Counting Sort

- Merge Sort/MergeSort-Python/Algorithm.txt
- Merge Sort/MergeSort-Python/MergeSort.py
Added the Algorithm file and the .py file for the MergeSort Algorithm
> Added MergeSort for Python

- Bubble Sort/BubbleSortC++/BubbleSort algo.txt
- Bubble Sort/BubbleSortC++/BubbleSort.cpp
Issue #1 
Added program for Bubble Sorting in C++ with algorithm explained text file.
> Added BubbleSort algorithm in C++

- Selection Sort/SelectionSort-C++/Selection Sorting algo.txt
- Selection Sort/SelectionSort-C++/SelectionSort.cpp
Issue #1 
Added C++ program for Selection Sort algorithm along with the text file in which algorithm is explained.
> Added SelectionSort algorithm program in C++

- Bogosort/BogoSort-C++/BogoSort-C++.c
> Implemented Bogo Sort for C++

- Merge Sort/MergeSort-C++/mergeSort.cpp
Added merge sort algorithm in C++
> Added merge sort algorithm in C++

- Counting sort/CountingSort-JavaScript/CountingSort.js
- Counting sort/CountingSort-JavaScript/CountingSort.txt
> CountingSort Javascript

- Selection Sort/SelectionSort-C/SelectionSort.c
- Selection Sort/SelectionSort-C/SelectionSort.txt
Hi there, I added a selection sort for C. I am pretty new to this open source thing, and relatively new to programming as well. Thank you for the opportunity to contribute!
> Added selection sort for C

- Gnome sort/Gnome sort-Python/gnome_sort.py
- Gnome sort/Gnome sort-Python/gnome_sort.txt
Issue #1 
Created ```Gnome sort``` and ```Gnome sort-Python``` folders, added a description of the algorithm and a Python implementation.
> Add Gnome sort implementation in Python

- Quick Sort/QuickSort-Javascript/QuickSort-Javascript.js
Implemented quicksort with javascript :D
> [HACKTOBERFEST] - Implemented quicksort with javascript

- Bogosort/BogoSort-Ruby/bogosort.rb
My solution for bogo sort in magnificent rubylang 💎
> Bogosort in Ruby

- CocktailSort/cocktailsort_python.py
- CocktailSort/cocktailsort_python.txt
- CocktailSort/cocktailsort_python_question.txt
- CocktailSort/cocktailsort_python_solution.txt
> Added Cocktail Sort in Python

- Quick Sort/QuickSort-Go/quicksort.go
I have added the Implementation of the Quick Sort Algorithm in Golang. Kindly review the same.
> Adding Go Implementation of Quick Sort

- Pancake Sort/Pancake Sort Intuition.txt
- Pancake Sort/Pancake Sort.py
Have added Pancake Sort implemented in Python. Change also includes said algorithm's intuition. Kindly review!
> Added Pancake Sort

- Bubble Sort/BubbleSortScala/Bubble Sort algo.txt
- Bubble Sort/BubbleSortScala/BubbleSort.scala
Implemented bubble sort in scala in functional style.
> Bubble Sort implementation in Scala

- Insertion Sort/Insertion-sort-Javascript/insertion_sort.js
Implemented insertion sort in javascript.
> added insertion_sort-javascript

- Bubble Sort/BubbleSortC/C-Sorting-Of-Dates.c
This program checks if the 5 dates entered are valid or not.
If valid, it sorts them.
If invalid, it asks you for another valid date.
The program is a direct extension of Bubble Sort and is very useful.
> Added Date Sorting using Bubble Sort in C

- Quick Sort/QuickSort-Kotlin/QuickSort.kt
This PR adds new QuickSort implementation in Kotlin. Issue reference: #1
> Add QuickSort in Kotlin

- Selection Sort/SelectionSort-Kotlin/SelectionSort.kt
This PR adds new SelectionSort implementation in Kotlin. Issue reference: #1
> Add SelectionSort in Kotlin

- Merge Sort/MergeSort-Kotlin/MergeSort.kt
This PR adds new MergeSort implementation in Kotlin. Issue reference: #1
> Add MergeSort in Kotlin

- Insertion Sort/Insertion-sort-Kotlin/InsertionSort.kt
This PR adds new InsertionSort implementation in Kotlin. Issue reference: #1
> Add InsertionSort in Kotlin

- CocktailSort/Cocktail Sort - Java/CocktailSort.java
I have added cocktail sort in java.
> Cocktail sort in Java added

- Shell sort/ShellSortJavascript/ShellSort.js
> Add ShellShort in Javascript

- brick sort-python
arr = [34, 2, 10, -9] 
n = len(arr) 
oddEvenSort(arr, n); 
for i in range(0, n): 
print(arr[i], end =" ")
> Create brick sort-python

- Bead Sort/BeadSort-Java/BeadSort.java
> Add Bead Sort in Java

- Quick Sort/QuickSort-Dart/QuickSort.dart.txt
QuickSort algorithm by jaskarans2000
> Added implementation of quicksort in dart

- Bitonic Sort/Bitonic Sort - Java/BitonicSort.java
Bitonic Sort Algorithm in Java created.
> Added Bitonic Sort

- Topological Sort/Topological_Sort_Java/TopologicalSort.java
- Topological Sort/topological-java-implementation.txt
Added Topological Sort implementation using Depth First Search
> Added Topological Sort

- Bitonic Sort/Bitonic Sort.txt
Added txt file explaining the Bitonic Sort Algorithm.
> Bitonic Sort Explained

- Bubble Sort/BubbleSortTypescript/bubbleSort.ts
- Merge Sort/MergeSort-Typescript/mergeSort.ts
- Shell sort/ShellSortJava/ShellSort.java
H, I just added BubbleSortTypescript
> Added algorithm-BubbleSortTypescript

- TimSort/TimSort_Java/Algorithm.txt
- TimSort/TimSort_Java/TimSort_Java.java
Hi tulika-99!
Added a TimSort algorithm in Java.
Thanks for the opportunity.
Have a good one.
> Add TimSort in Java

- Radix Sort/RadixSort-Go/RadixSort.go
> add radixsort.go

- Topological Sort/Topological_Sort_Java/TopologicalSort.java
- Topological Sort/topological-java-implementation.txt
> added comments

- StoogeSort/StoogeSort_Python
Added Stooge Sorting in Python. Hope you like it. :-)
> Added Stooge Sorting

- Brick Sort/brick-sort.go
Add brick sort realisation on Go
Signed-off-by: Kemalelee <kemalele17@gmail.com>
> Add brick sort realisation on Go

- Smooth sort/smooth sort in/smooth sort in VB.net/VB.net code
Smooth sort is a great technique and therefore added it in 4 languages.
> Added Smooth Sort

- Brick Sort/brickSort-C/brickSort-C.c
- Heap Sort/heapSort.c
- Radix Sort/RadixSort-C/radix_Sort.c
Locations=>
1. Brick Sort/brickSort-C/brickSort-C.c
2. Heap Sort/heapSort.c
3. Radix Sort/RadixSort-C/radix_Sort.c
> Added implementation of  heap sort, radix sort and brick sort in C

- Bubble Sort/BubbleSort-Bash/Bubble Sort.txt
- Bubble Sort/BubbleSort-Bash/BubbleSort.sh
Implemented Bubble sort algorithm using Bash
> Bubble sort in Bash

- Tree Sort/TreeSortPython/TreeSort.py
- Tree Sort/TreeSortPython/TreeSort.txt
Added a TreeSort algorithm implementation in Python along with an explanation of the algorithm, and its complexity analysis.
> Added TreeSort implementation in Python

- Bubble Sort/BubbleSortPHP/bubble sort algo.txt
- Bubble Sort/BubbleSortPHP/bubbleSort.php
Added Bubble Sort Algorithm(Sorting Algorithm) Implemented Using PHP.
> Added Bubble Sort

- 3_Way Merge Sort/ThreeWayMergeSort.java
> 3 way Merge Sort-Java

- Pigeonhole Sort/Pigeonhole_Sort-C/pigeonhole-sort.c
Added Pigeonhole sort algorithm in C language
> Created Pigeonhole_Sort-C folder

- Cycle Sort/Cycle_Sort_Java.java
- Cycle Sort/Cycle_Sort_Python.py
- OddEven Sort/OddEvenSort_Java.java
- OddEven Sort/OddEvenSort_Python.py
> Odd Even sort Using Python3

- Cycle Sort/Cycle_Sort_Java.java
- Cycle Sort/Cycle_Sort_Python.py
> Cycle sort java

- TimSort/TimSort_Python/TimSort.py
This is part of a commentary in #160 
Hi! This is an implementation of the TimSort algorithm written in python. Hope everything is ok and if not I will be happy to fix anything that is necessary. Cheers!
> Add TimSort algorithm in python

- IntroSort/IntroSort-cpp/Introsort.cpp
- IntroSort/IntroSort-cpp/algorithm.txt
> added IntroSort

- Counting sort/CountingSort-TypeScript/CountingSort.ts
- Counting sort/CountingSort-TypeScript/CountingSort.txt
I have added Counting Sort in TypeScript accordingly to the instructions given in this project.
> Added CountingSort-TypeScript

- Insertion Sort/Insertion Sort-Java/InsertionSortJava.java
- Insertion Sort/Insertion Sort-Java/insertion-algo.txt
Added Insertion Sort in java which takes input from the user and sorts by insertion sort algorithm.
> Added Insertion sort

- Bead Sort/BeadSort-Java/bead sort in c
thanks for reading my pull request
> bead sort in c

- Patience Sort/PatienceSort.cpp
> solves issue #222
